version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${DOCKER_PROJECT_ROOT:-.}/data:/app/backend/data
      - ${DOCKER_PROJECT_ROOT:-.}/players:/app/backend/static/players
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_PATH=/app/backend/data/db.sqlite3
      - SPOND_USERNAME=${SPOND_USERNAME}
      - SPOND_PASSWORD=${SPOND_PASSWORD}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  static_volume:
